### ISSUE TITLE
Using remaining samples in eachbatch

### ISSUE THREAD

**Issue by theogf** [JuliaML/MLDataPattern.jl#36] opened 2020-01-23 11:05 UTC
Hi!
Thanks for all the wonderful features of the package, they became essential to me!
I have one remark concerning `eachbatch`. Currently for a fixed `size`, `eachbatch` will ignore the last remaining samples.
Would there be a possibility to add a keyword that would change this behavior and return a smaller batch to parse the whole data?

**Comment by theogf** [comment] 2020-01-23 11:27
I just found out about `maxsize` (which is undocumented by the way :) ), but does not do what I described above

**Comment by oxinabox** [comment] 2020-01-23 12:35
Is this a duplicate of:
https://github.com/JuliaML/MLDataPattern.jl/issues/14 ?

**Comment by theogf** [comment] 2020-01-23 12:39
Oh yes I did not see it!
Well at least I am happy it revives the topic :smiley: 
Should I close the issue?

**Closed** 2020-01-23 12:44 UTC
